development:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: render-deploy_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: render-deploy_production
